//PROJECTS

GET http://localhost:5000/api/projects

###

GET http://localhost:5000/api/projects/1

###

POST http://localhost:5000/api/projects HTTP/1.1
content-type: application/json

{
    "name": "Complete my web sprint challenge in time.",
    "description": "The longest web sprint ever."
}

###

PUT http://localhost:5000/api/projects/6 HTTP/1.1
content-type: application/json

{
    "name": "Complete my web sprint challenge in time.",
    "description": "No way, it's cool.",
    "completed":true
}

###

DELETE http://localhost:5000/api/projects/5 HTTP/1.1

###

//ACTIONS

GET http://localhost:5000/api/actions

###

GET http://localhost:5000/api/actions/1

###

POST http://localhost:5000/api/actions HTTP/1.1
content-type: application/json

{
    "project_id": 2,
    "description": "fake install of whatever is needed.",
    "notes": "lots and lots of notes."
}

###

PUT http://localhost:5000/api/actions/1 HTTP/1.1
content-type: application/json

{
    "project_id": 1,
    "description": "Fork and Clone Repository",
    "notes": "Repo URL: https://github.com/LambdaSchool/Sprint-Challenge-Node-Express",
    "completed": false
}

###

DELETE http://localhost:5000/api/actions/4 HTTP/1.1

###

GET http://localhost:5000/api/projects/1/actions HTTP/1.1 

###
